### ISSUE TITLE
cannot install

### ISSUE THREAD

**Issue by wtliao** [fastai/course22p2#1]
Hi, I try to install this repo using the command:
`pip install course22p2`

but I got the error:
ERROR: Could not find a version that satisfies the requirement course22p2 (from versions: none)
ERROR: No matching distribution found for course22p2

I am using mac and tried to install it in a conda env.

**Comment by Meta-Sean** [comment]
I believe this is just nbdev boilerplate and this repo is still under construction ie (the readme needs to be udpated).  If you want to install this repo just use the trusty https://github.com/fastai/course22p2.git.

**Comment by Shuyib** [comment]
Hi @

> I believe this is just nbdev boilerplate and this repo is still under construction ie (the readme needs to be udpated). If you want to download this repo just use the trusty git clone https://github.com/fastai/course22p2.git.

@wtliao In virtual environment preferably python 3.10.* and above you could. Just reviewing the readme.
cd into the directory  

```bash
cd course22p2
```    
Then do a pip install  
```bash
pip install -e .
```
